[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
log = "0.4.21"
r-efi = "5.2.0"
serde-json-core = "0.6.0"
uguid = "2.2.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
